import { EventItem, Speaker, Sponsor, StallExpo } from "@/types/database";

export const initialEvents: EventItem[] = [
  {
    id: "pre-1",
    slug: "confluence",
    name: "Confluence",
    type: "pre_event",
    description: "IEDC Annual Confluence pre-event gathering.",
    spec: "Pre-Event",
    date_time: "Pre-Launch",
    venue: "CEV Premises",
    link: "",
    poster_url: "/pre-events/franklin.webp",
    completed_poster_url: "/pre-events/franklin_completed.webp",
    is_completed: true,
    is_closed: false,
    order_index: 1,
  },
  {
    id: "pre-2",
    slug: "whats-vibe-coding",
    name: "What's Vibe Coding",
    type: "pre_event",
    description: "Hands-on session exploring AI assisted rapid coding and vibe coding.",
    spec: "AI Workshop",
    date_time: "Pre-Launch",
    venue: "Programming Lab",
    link: "",
    poster_url: "/pre-events/vibecoding.webp",
    completed_poster_url: "/pre-events/vibecoding_completed.webp",
    is_completed: true,
    is_closed: false,
    order_index: 2,
  },
  {
    id: "pre-3",
    slug: "whats-supabase",
    name: "What's Supabase",
    type: "pre_event",
    description: "Learn how to build fullstack applications with Supabase backend.",
    spec: "Backend Tech",
    date_time: "Pre-Launch",
    venue: "CCF",
    link: "",
    poster_url: "/pre-events/supabase.webp",
    completed_poster_url: "/pre-events/supabase_completed.webp",
    is_completed: true,
    is_closed: false,
    order_index: 3,
  },
  {
    id: "main-1",
    slug: "alumni-interaction-meet",
    name: "IEDC Alumni Interaction Meet",
    type: "main_event",
    description: "Exclusive meetup with distinguished CEV IEDC alumni.",
    spec: "Only for pass out Students",
    date_time: "Oct 08 2025 | 9 AM - 4 PM",
    venue: "IEDC TOWN | CEV Premises",
    link: "",
    poster_url: "/events/alumini.webp",
    completed_poster_url: "",
    is_completed: false,
    is_closed: true,
    order_index: 1,
  },
  {
    id: "main-2",
    slug: "bit-burst-2",
    name: "BIT'BURST 2.0",
    type: "main_event",
    description: "24-Hour premier collegiate coding marathon.",
    spec: "Exclusively for CEV Students",
    date_time: "Oct 06 - 07 2025 | 4 PM | 24 hrs",
    venue: "CCF, Programming Lab",
    link: "",
    poster_url: "/events/bitburst.webp",
    completed_poster_url: "",
    is_completed: false,
    is_closed: true,
    order_index: 2,
  },
  {
    id: "main-3",
    slug: "visio",
    name: "Visio",
    type: "main_event",
    description: "AI image & video exhibition and contest.",
    spec: "AI image & video exhibition",
    date_time: "Oct 08 2025 | 9 AM - 4 PM",
    venue: "Lyra | CEV Premises",
    link: "",
    poster_url: "/events/visio_ai.webp",
    completed_poster_url: "",
    is_completed: false,
    is_closed: true,
    order_index: 3,
  },
  {
    id: "main-4",
    slug: "pitchbox",
    name: "PitchBox",
    type: "main_event",
    description: "Idea pitching competition for student entrepreneurs.",
    spec: "Idea pitching competition",
    date_time: "Oct 08 2025 | 1 PM - 4 PM",
    venue: "Astra | CEV Premises",
    link: "",
    poster_url: "/events/pitchbox.webp",
    completed_poster_url: "",
    is_completed: false,
    is_closed: true,
    order_index: 4,
  },
  {
    id: "main-5",
    slug: "hack-4-ease",
    name: "Hack 4 Ease",
    type: "main_event",
    description: "Social impact innovation hackathon.",
    spec: "Social impact hackathon",
    date_time: "Oct 08 2025 | 10 AM - 1 PM",
    venue: "Eclipse | CEV Premises",
    link: "",
    poster_url: "/events/hack4ease.webp",
    completed_poster_url: "",
    is_completed: false,
    is_closed: true,
    order_index: 5,
  },
  {
    id: "main-6",
    slug: "quizzard-college",
    name: "Quizzard",
    type: "main_event",
    description: "College Level Quiz Competition.",
    spec: "College Level Quiz Competition",
    date_time: "Oct 08 2025 | 1:30 PM - 3 PM",
    venue: "Orion | CEV Premises",
    link: "",
    poster_url: "/events/quizzards_college.webp",
    completed_poster_url: "",
    is_completed: false,
    is_closed: true,
    order_index: 6,
  },
  {
    id: "main-7",
    slug: "iedc-leads-meet",
    name: "IEDC Leads Meet",
    type: "main_event",
    description: "Networking event for regional IEDC student leads.",
    spec: "Networking event for IEDC leads",
    date_time: "Oct 08 2025 | 9 AM - 4 PM",
    venue: "IEDC TOWN | CEV Premises",
    link: "",
    poster_url: "/events/leadsmeet.webp",
    completed_poster_url: "",
    is_completed: false,
    is_closed: true,
    order_index: 7,
  }
];

export const initialStalls: StallExpo[] = [
  {
    id: "stall-1",
    name: "Innoverse",
    image_url: "/stalls/innoverse.webp",
    description: "A product development expo based on AI powered Automation and Robotics.",
    order_index: 1,
  },
  {
    id: "stall-2",
    name: "Robo Soccer",
    image_url: "/stalls/robo_soccer.webp",
    description: "Finite Intelligence presents Robo Soccer, based on AI powered Robotics.",
    order_index: 2,
  },
  {
    id: "stall-3",
    name: "Talrop Ecosystem",
    image_url: "/stalls/talrop.webp",
    description: "Diverse startups and innovations by Talrop, a leading talent solutions company.",
    order_index: 3,
  },
  {
    id: "stall-4",
    name: "FOSS Corner",
    image_url: "/stalls/foss.webp",
    description: "Explore the world of Free and Open Source Software (FOSS) with us.",
    order_index: 4,
  },
  {
    id: "stall-5",
    name: "Mu Corner",
    image_url: "/stalls/mucorner.webp",
    description: "Discover the latest in games and interactive experiences with Mu Learn.",
    order_index: 5,
  }
];

export const initialSpeakers: Speaker[] = [
  {
    id: "speaker-1",
    name: "Nandu Krishna T",
    designation: "CTO Lofritex IT Solutions",
    expertise: "Full Stack Developer",
    image_url: "/speakers/nandu_krishna.webp",
    order_index: 1,
  },
  {
    id: "speaker-2",
    name: "Rony K Roy",
    designation: "Sr. Technology Fellow",
    expertise: "Kerala Startup Mission",
    image_url: "/speakers/rony.webp",
    order_index: 2,
  },
  {
    id: "speaker-3",
    name: "Adhish Chakyery",
    designation: "Co Founder & CEO",
    expertise: "Meda (Abix Global Group)",
    image_url: "/speakers/adhish.webp",
    order_index: 3,
  },
  {
    id: "speaker-4",
    name: "Rajath Navas",
    designation: "CEO & Founder",
    expertise: "Pace Lab",
    image_url: "/speakers/rajath.webp",
    order_index: 4,
  },
  {
    id: "speaker-5",
    name: "Musfira Parvin K",
    designation: "Vice President Of Business Development",
    expertise: "Talrop",
    image_url: "/speakers/musfi.webp",
    order_index: 5,
  },
  {
    id: "speaker-6",
    name: "Muhammed Jaseel",
    designation: "Co Founder",
    expertise: "Kalibah Trading LLP",
    image_url: "/speakers/jaseel.webp",
    order_index: 6,
  },
  {
    id: "speaker-7",
    name: "Ahammed Kabeer",
    designation: "Founder & CEO",
    expertise: "Mirrorfolio",
    image_url: "/speakers/kabeerr.webp",
    order_index: 7,
  }
];

export const initialSponsors: Sponsor[] = [
  {
    id: "sponsor-1",
    name: "Made Products",
    image_url: "/sponsors/made_cover.webp",
    category: "Title Sponsor",
    order_index: 1,
  },
  {
    id: "sponsor-2",
    name: "Cake Stories",
    image_url: "/sponsors/cake_stories.webp",
    category: "Associate Sponsor",
    order_index: 2,
  },
  {
    id: "sponsor-3",
    name: "Finite Intelligence",
    image_url: "/sponsors/finite_intelligence.webp",
    category: "Tech Partner",
    order_index: 3,
  },
  {
    id: "sponsor-4",
    name: "Snaptiqz",
    image_url: "/sponsors/snaptiqz.webp",
    category: "Media Partner",
    order_index: 4,
  }
];
